common:
  executable_path: ../../../../bin/x64/Release/Newxim.exe
  config_path: ../../../../Newxim/config.yml
  value_start: 0
  value_step: 0.01
  value_stop: 0.6
  exporter: CSV
  workers_pool_size: 8
  arguments:
    packet_injection_rate: '%'
    #scale_with_nodes: true
    

configurations:
- output_path: RS C(36, 1, 2, 3, 4, 5, 6, 7, 8, 9).csv
  arguments:
    topology: CIRCULANT
    topology_args: '[36, 1, 2, 3, 4, 5, 6, 7, 8, 9]'
    routing_algorithm: TABLE_BASED
    selection_strategy: CIRCULANT_VIRTUAL_RING_SPLIT